// Initial AIVEXA catalog — real, well known AI services.
// IMPORTANT: affiliate links are intentionally empty (is_affiliate = "no").
// The owner adds them later from the admin panel.

export const CATEGORIES = [
  { slug: "assistants", icon: "🧠", name_ru: "AI-помощники", name_uk: "AI-помічники", name_en: "AI assistants", order_position: 1, keywords: "ассистент, чат-бот, помощник, вопрос, ответ, chat, assistant, chatbot, помічник, спросить, gpt" },
  { slug: "image", icon: "🎨", name_ru: "Изображения", name_uk: "Зображення", name_en: "Images", order_position: 2, keywords: "изображение, картинка, фото, рисунок, логотип, дизайн, арт, фон, image, picture, photo, logo, design, art, background, зображення, малюнок, логотип" },
  { slug: "video", icon: "🎬", name_ru: "Видео", name_uk: "Відео", name_en: "Video", order_position: 3, keywords: "видео, ролик, монтаж, аватар, клип, reels, shorts, tiktok, video, editing, avatar, clip, відео, монтаж, кліп" },
  { slug: "writing", icon: "✍️", name_ru: "Тексты", name_uk: "Тексти", name_en: "Writing", order_position: 4, keywords: "текст, статья, копирайтинг, письмо, рерайт, грамматика, text, writing, copywriting, article, rewrite, grammar, текст, стаття, копірайтинг" },
  { slug: "voice", icon: "🎙️", name_ru: "Голос", name_uk: "Голос", name_en: "Voice", order_position: 5, keywords: "голос, озвучка, озвучить, речь, дубляж, подкаст, tts, voice, speech, dubbing, podcast, voiceover, озвучення, мовлення" },
  { slug: "music", icon: "🎵", name_ru: "Музыка", name_uk: "Музика", name_en: "Music", order_position: 6, keywords: "музыка, песня, трек, бит, саундтрек, music, song, track, beat, soundtrack, музика, пісня, трек" },
  { slug: "code", icon: "💻", name_ru: "Код", name_uk: "Код", name_en: "Code", order_position: 7, keywords: "код, программирование, разработка, сайт, приложение, code, programming, development, app, website, код, програмування, розробка" },
  { slug: "business", icon: "📊", name_ru: "Бизнес", name_uk: "Бізнес", name_en: "Business", order_position: 8, keywords: "бизнес, презентация, автоматизация, встречи, аналитика, продажи, business, presentation, automation, meetings, analytics, бізнес, презентація, автоматизація" },
  { slug: "social", icon: "📱", name_ru: "Соцсети", name_uk: "Соцмережі", name_en: "Social media", order_position: 9, keywords: "соцсети, инстаграм, тикток, посты, контент, smm, social, instagram, tiktok, posts, content, соцмережі, пости" },
  { slug: "documents", icon: "📄", name_ru: "Документы", name_uk: "Документи", name_en: "Documents", order_position: 10, keywords: "документы, pdf, файлы, договор, резюме, documents, files, contract, resume, документи, файли" },
  { slug: "translation", icon: "🌍", name_ru: "Перевод", name_uk: "Переклад", name_en: "Translation", order_position: 11, keywords: "перевод, переводчик, языки, локализация, translate, translation, languages, localization, переклад, перекладач, мови" },
  { slug: "education", icon: "🎓", name_ru: "Образование", name_uk: "Освіта", name_en: "Education", order_position: 12, keywords: "образование, учеба, учить, язык, репетитор, курсы, education, learning, study, tutor, courses, освіта, навчання" },
];

const s = (data) => data;

const PART1 = [
  s({
    name: "ChatGPT", slug: "chatgpt", cat: "assistants", domain: "openai.com",
    url: "https://chatgpt.com/", free: "yes", price_type: "freemium", price: "Free / Plus $20",
    rating: 4.9, popularity: 100, popular: "yes", featured: "yes",
    tags: "чат-бот, ассистент, тексты, код, анализ",
    keywords: "chatgpt, чат гпт, gpt, openai, ассистент, помощник, написать текст, написать код, идеи, перевести, chat bot, помічник, асистент",
    ru: {
      d: "Самый популярный AI-ассистент от OpenAI: пишет и редактирует тексты, генерирует код, анализирует файлы и изображения, ищет информацию в интернете.",
      f: ["Генерация и редактирование текстов", "Написание и отладка кода", "Анализ файлов, таблиц и изображений", "Голосовой режим и поиск в интернете"],
      p: ["Универсальность для любых задач", "Огромная база знаний", "Бесплатный тариф без ограничения по времени"],
      c: ["Расширенные модели только на платном тарифе", "Может ошибаться в фактах"],
    },
    en: {
      d: "The most popular AI assistant by OpenAI: writes and edits text, generates code, analyses files and images, and searches the web.",
      f: ["Text generation and editing", "Code writing and debugging", "File, spreadsheet and image analysis", "Voice mode and web search"],
      p: ["Works for almost any task", "Huge knowledge base", "Free tier with no time limit"],
      c: ["Advanced models are paid only", "Can get facts wrong"],
    },
  }),
  s({
    name: "Claude", slug: "claude", cat: "assistants", domain: "anthropic.com",
    url: "https://claude.ai/", free: "yes", price_type: "freemium", price: "Free / Pro $20",
    rating: 4.8, popularity: 92, popular: "yes", featured: "yes",
    tags: "чат-бот, длинные тексты, код, анализ документов",
    keywords: "claude, клод, anthropic, ассистент, длинный текст, анализ документа, написать код, эссе, помічник",
    ru: {
      d: "AI-ассистент Anthropic, сильный в работе с длинными документами, аналитикой и написанием качественного кода.",
      f: ["Работа с очень длинными документами", "Аккуратный и структурный стиль письма", "Сильные навыки программирования", "Загрузка PDF и изображений"],
      p: ["Отлично держит контекст больших текстов", "Меньше «воды» в ответах", "Есть бесплатный тариф"],
      c: ["Лимиты сообщений на бесплатном тарифе", "Нет генерации изображений"],
    },
    en: {
      d: "Anthropic's AI assistant, strong at long documents, analysis and writing high quality code.",
      f: ["Handles very long documents", "Clean and structured writing style", "Strong coding skills", "PDF and image uploads"],
      p: ["Keeps context of large texts", "Less fluff in answers", "Free tier available"],
      c: ["Message limits on the free plan", "No image generation"],
    },
  }),
  s({
    name: "Google Gemini", slug: "gemini", cat: "assistants", domain: "gemini.google.com",
    url: "https://gemini.google.com/", free: "yes", price_type: "freemium", price: "Free / AI Pro $19.99",
    rating: 4.7, popularity: 88, popular: "yes", featured: "no",
    tags: "чат-бот, google, поиск, мультимодальность",
    keywords: "gemini, гемини, google, bard, ассистент, поиск, документы, gmail, помічник",
    ru: {
      d: "AI-ассистент Google с доступом к актуальному поиску и интеграцией с Gmail, Документами и Диском.",
      f: ["Ответы с опорой на поиск Google", "Интеграция с Gmail, Docs и Drive", "Анализ изображений и видео", "Генерация изображений"],
      p: ["Бесплатный доступ к сильной модели", "Тесная связь с сервисами Google", "Хорошо работает с актуальными данными"],
      c: ["Качество ответов нестабильно", "Часть функций недоступна в некоторых странах"],
    },
    en: {
      d: "Google's AI assistant with live search access and integration into Gmail, Docs and Drive.",
      f: ["Answers grounded in Google Search", "Gmail, Docs and Drive integration", "Image and video analysis", "Image generation"],
      p: ["Strong model available for free", "Deep Google ecosystem integration", "Good with fresh data"],
      c: ["Answer quality can be inconsistent", "Some features are region locked"],
    },
  }),
  s({
    name: "Perplexity", slug: "perplexity", cat: "assistants", domain: "perplexity.ai",
    url: "https://www.perplexity.ai/", free: "yes", price_type: "freemium", price: "Free / Pro $20",
    rating: 4.7, popularity: 80, popular: "yes", featured: "no",
    tags: "поиск, исследования, источники, ответы",
    keywords: "perplexity, перплексити, поиск, найти информацию, исследование, источники, research, пошук",
    ru: {
      d: "AI-поисковик, который отвечает на вопросы и всегда показывает ссылки на источники — удобен для ресёрча.",
      f: ["Ответы со ссылками на источники", "Режим глубокого исследования", "Поиск по научным статьям", "Коллекции для проектов"],
      p: ["Прозрачные источники под каждым ответом", "Отлично подходит для ресёрча", "Быстрая работа"],
      c: ["Хуже подходит для творческих текстов", "Лимиты Pro-запросов на бесплатном тарифе"],
    },
    en: {
      d: "An AI search engine that answers questions and always cites its sources — great for research.",
      f: ["Answers with source citations", "Deep research mode", "Academic paper search", "Collections for projects"],
      p: ["Transparent sources for every answer", "Excellent for research", "Very fast"],
      c: ["Weaker at creative writing", "Pro query limits on the free plan"],
    },
  }),
  s({
    name: "DeepSeek", slug: "deepseek", cat: "assistants", domain: "deepseek.com",
    url: "https://chat.deepseek.com/", free: "yes", price_type: "free", price: "Бесплатно",
    rating: 4.5, popularity: 70, popular: "no", featured: "no",
    tags: "чат-бот, бесплатно, код, рассуждения",
    keywords: "deepseek, дипсик, бесплатный чат бот, код, математика, рассуждения, безкоштовний",
    ru: {
      d: "Бесплатный AI-ассистент с сильными способностями в математике, логике и программировании.",
      f: ["Режим пошаговых рассуждений", "Сильная математика и логика", "Генерация кода", "Полностью бесплатный чат"],
      p: ["Бесплатный доступ без подписки", "Хорошо решает технические задачи", "Открытые модели"],
      c: ["Интерфейс проще, чем у конкурентов", "Возможны перебои при высокой нагрузке"],
    },
    en: {
      d: "A free AI assistant with strong math, logic and programming abilities.",
      f: ["Step-by-step reasoning mode", "Strong math and logic", "Code generation", "Completely free chat"],
      p: ["Free access, no subscription", "Great at technical tasks", "Open weight models"],
      c: ["Simpler interface than rivals", "Can be slow under heavy load"],
    },
  }),
];

const PART2 = [
  s({
    name: "Midjourney", slug: "midjourney", cat: "image", domain: "midjourney.com",
    url: "https://www.midjourney.com/", free: "no", price_type: "paid", price: "от $10/мес",
    rating: 4.8, popularity: 95, popular: "yes", featured: "yes",
    tags: "генерация изображений, арт, иллюстрации, дизайн",
    keywords: "midjourney, миджорни, создать изображение, картинка, арт, иллюстрация, нарисовать, image generation, згенерувати зображення",
    ru: {
      d: "Эталон генерации изображений: создаёт художественные иллюстрации, концепт-арт и рекламные визуалы по текстовому описанию.",
      f: ["Генерация изображений по тексту", "Редактирование и расширение картинок", "Стилевые референсы", "Веб-редактор и Discord"],
      p: ["Лучшее художественное качество на рынке", "Огромное сообщество и подсказки", "Быстрая генерация"],
      c: ["Нет бесплатного тарифа", "Требуется привыкнуть к параметрам"],
    },
    en: {
      d: "The benchmark for image generation: artistic illustrations, concept art and ad visuals from a text prompt.",
      f: ["Text to image generation", "Image editing and outpainting", "Style references", "Web editor and Discord"],
      p: ["Best artistic quality available", "Huge community and prompt library", "Fast generation"],
      c: ["No free plan", "Parameters take time to learn"],
    },
  }),
  s({
    name: "Leonardo AI", slug: "leonardo-ai", cat: "image", domain: "leonardo.ai",
    url: "https://leonardo.ai/", free: "yes", price_type: "freemium", price: "Free / от $12",
    rating: 4.6, popularity: 74, popular: "no", featured: "no",
    tags: "генерация изображений, гейм-арт, бесплатно",
    keywords: "leonardo ai, леонардо, создать изображение, бесплатно картинка, game art, концепт, зображення",
    ru: {
      d: "Генератор изображений с бесплатными ежедневными кредитами, набором готовых моделей и удобным редактором.",
      f: ["Бесплатные ежедневные кредиты", "Готовые модели под разные стили", "Canvas-редактор и inpainting", "Генерация текстур и 3D-ассетов"],
      p: ["Щедрый бесплатный тариф", "Много стилевых пресетов", "Удобно для геймдева и дизайна"],
      c: ["Кредиты быстро заканчиваются", "Интерфейс перегружен настройками"],
    },
    en: {
      d: "An image generator with free daily credits, a library of ready models and a convenient editor.",
      f: ["Free daily credits", "Ready made style models", "Canvas editor and inpainting", "Texture and 3D asset generation"],
      p: ["Generous free tier", "Lots of style presets", "Great for gamedev and design"],
      c: ["Credits run out quickly", "Interface is packed with settings"],
    },
  }),
  s({
    name: "Ideogram", slug: "ideogram", cat: "image", domain: "ideogram.ai",
    url: "https://ideogram.ai/", free: "yes", price_type: "freemium", price: "Free / от $8",
    rating: 4.6, popularity: 66, popular: "no", featured: "no",
    tags: "изображения, текст на картинке, постеры, логотипы",
    keywords: "ideogram, идеограм, текст на изображении, постер, логотип, надпись, typography, зображення з текстом",
    ru: {
      d: "Генератор изображений, который лучше всех рисует читаемый текст — идеален для постеров, логотипов и обложек.",
      f: ["Читаемый текст внутри изображения", "Шаблоны постеров и логотипов", "Магический промпт-помощник", "Бесплатные генерации каждый день"],
      p: ["Лучшая работа с надписями", "Простой интерфейс", "Есть бесплатный тариф"],
      c: ["Художественность ниже, чем у Midjourney", "Ограничения на бесплатном плане"],
    },
    en: {
      d: "The image generator that renders readable text best — perfect for posters, logos and covers.",
      f: ["Readable text inside images", "Poster and logo templates", "Magic prompt helper", "Free generations every day"],
      p: ["Best in class typography", "Simple interface", "Free tier available"],
      c: ["Less artistic than Midjourney", "Limits on the free plan"],
    },
  }),
  s({
    name: "remove.bg", slug: "remove-bg", cat: "image", domain: "remove.bg",
    url: "https://www.remove.bg/", free: "yes", price_type: "freemium", price: "Free / от $0.20 за фото",
    rating: 4.7, popularity: 78, popular: "yes", featured: "no",
    tags: "удаление фона, фото, товары, маркетплейсы",
    keywords: "remove bg, убрать фон, удалить фон с фото, вырезать объект, прозрачный фон, background remover, прибрати фон",
    ru: {
      d: "Сервис, который убирает фон с фотографии за пару секунд — для товаров, портретов и маркетплейсов.",
      f: ["Удаление фона в один клик", "Пакетная обработка", "Замена фона на цвет или картинку", "API и плагины для Photoshop"],
      p: ["Очень точное выделение волос и краёв", "Работает мгновенно", "Есть бесплатные превью"],
      c: ["HD-скачивание платное", "Узкая специализация"],
    },
    en: {
      d: "Removes the background from a photo in seconds — for products, portraits and marketplaces.",
      f: ["One click background removal", "Batch processing", "Replace background with colour or image", "API and Photoshop plugin"],
      p: ["Very accurate hair and edge cutout", "Instant results", "Free previews"],
      c: ["HD downloads are paid", "Single purpose tool"],
    },
  }),
  s({
    name: "Adobe Firefly", slug: "adobe-firefly", cat: "image", domain: "adobe.com",
    url: "https://firefly.adobe.com/", free: "yes", price_type: "freemium", price: "Free / от $9.99",
    rating: 4.5, popularity: 68, popular: "no", featured: "no",
    tags: "изображения, коммерческая лицензия, adobe, ретушь",
    keywords: "adobe firefly, файрфлай, изображение, генеративная заливка, photoshop, коммерческое использование, зображення",
    ru: {
      d: "Генеративный AI от Adobe с безопасной для коммерции лицензией и интеграцией в Photoshop и Express.",
      f: ["Генерация изображений и эффектов текста", "Генеративная заливка в Photoshop", "Безопасная коммерческая лицензия", "Смена стиля и расширение кадра"],
      p: ["Можно использовать в коммерции без рисков", "Встроен в продукты Adobe", "Простой и понятный интерфейс"],
      c: ["Качество ниже топовых генераторов", "Кредиты ограничены"],
    },
    en: {
      d: "Adobe's generative AI with a commercially safe licence and native Photoshop and Express integration.",
      f: ["Image and text effect generation", "Generative fill in Photoshop", "Commercially safe licence", "Style transfer and outpainting"],
      p: ["Safe for commercial use", "Built into Adobe apps", "Clean, simple interface"],
      c: ["Quality below top generators", "Limited credits"],
    },
  }),
  s({
    name: "Canva", slug: "canva", cat: "image", domain: "canva.com",
    url: "https://www.canva.com/", free: "yes", price_type: "freemium", price: "Free / Pro от $11.99",
    rating: 4.8, popularity: 90, popular: "yes", featured: "yes",
    tags: "дизайн, логотип, презентации, шаблоны, соцсети",
    keywords: "canva, канва, дизайн, создать логотип, презентация, обложка, баннер, шаблоны, магический дизайн, дизайн для инстаграм",
    ru: {
      d: "Онлайн-редактор дизайна с AI-инструментами: логотипы, посты, презентации и видео по готовым шаблонам.",
      f: ["Тысячи готовых шаблонов", "Magic Studio: генерация текста и картинок", "Удаление фона и ретушь", "Совместная работа команды"],
      p: ["Не нужны навыки дизайнера", "Огромная библиотека шаблонов", "Сильный бесплатный тариф"],
      c: ["Лучшие элементы доступны только в Pro", "Шаблоны легко узнаваемы"],
    },
    en: {
      d: "An online design editor with AI tools: logos, posts, presentations and videos from ready templates.",
      f: ["Thousands of ready templates", "Magic Studio text and image generation", "Background removal and retouch", "Team collaboration"],
      p: ["No design skills needed", "Massive template library", "Strong free tier"],
      c: ["Best assets are Pro only", "Templates look recognisable"],
    },
  }),
];

const PART3 = [
  s({
    name: "Runway", slug: "runway", cat: "video", domain: "runwayml.com",
    url: "https://runwayml.com/", free: "yes", price_type: "freemium", price: "Free / от $12",
    rating: 4.7, popularity: 86, popular: "yes", featured: "yes",
    tags: "генерация видео, спецэффекты, монтаж",
    keywords: "runway, ранвей, создать видео, генерация видео, video generation, спецэффекты, анимация фото, зробити відео",
    ru: {
      d: "Профессиональная студия генерации видео: создаёт ролики по тексту или оживляет статичное изображение.",
      f: ["Видео из текста и из фото", "Инструменты Motion Brush и Camera Control", "Удаление объектов и фона в видео", "Расширенный видеоредактор"],
      p: ["Кинематографичное качество", "Много профессиональных инструментов", "Есть бесплатные кредиты"],
      c: ["Кредиты расходуются очень быстро", "Долгий рендер на бесплатном тарифе"],
    },
    en: {
      d: "A professional video generation studio: makes clips from text or brings a still image to life.",
      f: ["Text to video and image to video", "Motion Brush and Camera Control", "Object and background removal in video", "Full video editor"],
      p: ["Cinematic quality", "Lots of professional tools", "Free credits included"],
      c: ["Credits burn very fast", "Slow rendering on the free plan"],
    },
  }),
  s({
    name: "Synthesia", slug: "synthesia", cat: "video", domain: "synthesia.io",
    url: "https://www.synthesia.io/", free: "yes", price_type: "freemium", price: "Free / от $18/мес",
    rating: 4.6, popularity: 76, popular: "yes", featured: "no",
    tags: "аватары, обучающее видео, презентации, дубляж",
    keywords: "synthesia, синтезия, аватар, видео с диктором, обучающее видео, презентация видео, avatar video, відео з аватаром",
    ru: {
      d: "Создание видео с реалистичным AI-аватаром, который произносит ваш текст на 140+ языках. Идеально для обучения и презентаций.",
      f: ["230+ готовых AI-аватаров", "Озвучка на 140+ языках", "Шаблоны корпоративных видео", "Клонирование собственного аватара"],
      p: ["Не нужна камера и студия", "Быстрое обновление контента", "Много языков для локализации"],
      c: ["Аватары выглядят формально", "Платные тарифы недешёвые"],
    },
    en: {
      d: "Create videos with a realistic AI avatar that speaks your script in 140+ languages. Perfect for training and presentations.",
      f: ["230+ ready AI avatars", "Voice over in 140+ languages", "Corporate video templates", "Custom avatar cloning"],
      p: ["No camera or studio needed", "Update content in minutes", "Many localisation languages"],
      c: ["Avatars look formal", "Paid plans are pricey"],
    },
  }),
  s({
    name: "HeyGen", slug: "heygen", cat: "video", domain: "heygen.com",
    url: "https://www.heygen.com/", free: "yes", price_type: "freemium", price: "Free / от $29/мес",
    rating: 4.6, popularity: 72, popular: "no", featured: "no",
    tags: "аватары, дубляж, липсинк, реклама",
    keywords: "heygen, хейген, аватар, перевод видео, дубляж, липсинк, ugc реклама, translate video, дубляж відео",
    ru: {
      d: "Видео с AI-аватарами и автоматический перевод роликов с синхронизацией губ на десятки языков.",
      f: ["AI-аватары и клонирование голоса", "Перевод видео с липсинком", "UGC-шаблоны для рекламы", "Интерактивные аватары"],
      p: ["Отличный перевод роликов", "Быстро делать рекламные креативы", "Есть бесплатные минуты"],
      c: ["Бесплатный тариф очень ограничен", "Иногда артефакты на липсинке"],
    },
    en: {
      d: "Videos with AI avatars plus automatic video translation with lip sync into dozens of languages.",
      f: ["AI avatars and voice cloning", "Video translation with lip sync", "UGC ad templates", "Interactive avatars"],
      p: ["Excellent video translation", "Fast ad creative production", "Free minutes included"],
      c: ["Very limited free tier", "Occasional lip sync artifacts"],
    },
  }),
  s({
    name: "Kling AI", slug: "kling-ai", cat: "video", domain: "klingai.com",
    url: "https://klingai.com/", free: "yes", price_type: "freemium", price: "Free / от $6.99",
    rating: 4.5, popularity: 64, popular: "no", featured: "no",
    tags: "генерация видео, анимация фото, эффекты",
    keywords: "kling ai, клинг, генерация видео, оживить фото, анимация изображения, video ai, оживити фото",
    ru: {
      d: "Генератор видео, который качественно оживляет фотографии и создаёт короткие ролики по описанию.",
      f: ["Видео из текста и из фото", "Контроль движения камеры", "Готовые видеоэффекты", "Ежедневные бесплатные кредиты"],
      p: ["Реалистичное движение", "Ежедневные бесплатные генерации", "Доступные цены"],
      c: ["Очередь на бесплатном тарифе", "Короткая длительность роликов"],
    },
    en: {
      d: "A video generator that animates photos convincingly and creates short clips from a description.",
      f: ["Text to video and image to video", "Camera motion control", "Ready made video effects", "Daily free credits"],
      p: ["Realistic motion", "Free generations every day", "Affordable pricing"],
      c: ["Queues on the free plan", "Short clip duration"],
    },
  }),
  s({
    name: "CapCut", slug: "capcut", cat: "video", domain: "capcut.com",
    url: "https://www.capcut.com/", free: "yes", price_type: "freemium", price: "Free / Pro от $9.99",
    rating: 4.6, popularity: 82, popular: "yes", featured: "no",
    tags: "монтаж, субтитры, tiktok, reels, шаблоны",
    keywords: "capcut, капкат, монтаж видео, субтитры, тикток, reels, shorts, обработать видео, монтаж відео",
    ru: {
      d: "Бесплатный видеоредактор с AI: автосубтитры, удаление фона, шаблоны для TikTok, Reels и Shorts.",
      f: ["Автоматические субтитры", "Удаление фона без хромакея", "Тысячи трендовых шаблонов", "AI-озвучка и ретушь"],
      p: ["Мощный бесплатный функционал", "Работает в браузере и на телефоне", "Идеален для коротких видео"],
      c: ["Водяные знаки у части шаблонов", "Экспорт 4K только в Pro"],
    },
    en: {
      d: "A free video editor with AI: auto captions, background removal and templates for TikTok, Reels and Shorts.",
      f: ["Automatic captions", "Background removal without a green screen", "Thousands of trending templates", "AI voice over and retouch"],
      p: ["Powerful free feature set", "Works in browser and on mobile", "Perfect for short form video"],
      c: ["Watermarks on some templates", "4K export is Pro only"],
    },
  }),
  s({
    name: "Opus Clip", slug: "opus-clip", cat: "video", domain: "opus.pro",
    url: "https://www.opus.pro/", free: "yes", price_type: "freemium", price: "Free / от $9/мес",
    rating: 4.5, popularity: 60, popular: "no", featured: "no",
    tags: "нарезка видео, shorts, клипы, субтитры",
    keywords: "opus clip, опус клип, нарезка видео, клипы из длинного видео, shorts, тикток из подкаста, нарізка відео",
    ru: {
      d: "Автоматически нарезает длинное видео на вертикальные клипы для TikTok, Reels и Shorts с субтитрами.",
      f: ["Автонарезка длинных видео", "Оценка виральности клипов", "Динамические субтитры", "Автокадрирование под 9:16"],
      p: ["Экономит часы монтажа", "Хорошо находит удачные моменты", "Есть бесплатные минуты"],
      c: ["Мало бесплатных минут", "Нужна проверка нарезок вручную"],
    },
    en: {
      d: "Automatically turns long videos into vertical clips for TikTok, Reels and Shorts with captions.",
      f: ["Auto clipping of long videos", "Virality score for each clip", "Dynamic captions", "Auto reframe to 9:16"],
      p: ["Saves hours of editing", "Finds strong moments well", "Free minutes included"],
      c: ["Few free minutes", "Clips still need manual review"],
    },
  }),
];

const PART4 = [
  s({
    name: "Jasper", slug: "jasper", cat: "writing", domain: "jasper.ai",
    url: "https://www.jasper.ai/", free: "no", price_type: "paid", price: "от $39/мес",
    rating: 4.4, popularity: 58, popular: "no", featured: "no",
    tags: "копирайтинг, маркетинг, бренд-голос, реклама",
    keywords: "jasper, джаспер, копирайтинг, маркетинговый текст, рекламный текст, брендовый голос, copywriting, копірайтинг",
    ru: {
      d: "Маркетинговая платформа для генерации рекламных текстов, лендингов и email-кампаний в едином голосе бренда.",
      f: ["Настройка голоса бренда", "50+ шаблонов маркетинговых текстов", "Кампании и командная работа", "Проверка на плагиат и SEO"],
      p: ["Тексты в стиле вашего бренда", "Много готовых форматов", "Заточен под маркетинг"],
      c: ["Нет бесплатного тарифа", "Дороже универсальных ассистентов"],
    },
    en: {
      d: "A marketing platform for ad copy, landing pages and email campaigns in a consistent brand voice.",
      f: ["Custom brand voice", "50+ marketing copy templates", "Campaigns and team collaboration", "Plagiarism and SEO checks"],
      p: ["Copy that matches your brand", "Many ready formats", "Built for marketing teams"],
      c: ["No free plan", "Pricier than general assistants"],
    },
  }),
  s({
    name: "Copy.ai", slug: "copy-ai", cat: "writing", domain: "copy.ai",
    url: "https://www.copy.ai/", free: "yes", price_type: "freemium", price: "Free / от $49/мес",
    rating: 4.4, popularity: 55, popular: "no", featured: "no",
    tags: "копирайтинг, продажи, email, автоматизация",
    keywords: "copy ai, копи аи, написать текст, продающий текст, email рассылка, посты, копірайтинг, написати текст",
    ru: {
      d: "Генератор продающих текстов и автоматизации для отделов маркетинга и продаж.",
      f: ["90+ шаблонов текстов", "Рабочие процессы для продаж", "Генерация email-цепочек", "Поддержка 25+ языков"],
      p: ["Быстрый старт без промптов", "Есть бесплатный тариф", "Интеграции с CRM"],
      c: ["Тексты требуют редактуры", "Платные тарифы дорогие"],
    },
    en: {
      d: "A sales copy generator with automation workflows for marketing and sales teams.",
      f: ["90+ copy templates", "Sales workflows", "Email sequence generation", "25+ languages"],
      p: ["Fast start without prompting", "Free tier available", "CRM integrations"],
      c: ["Output needs editing", "Paid plans are expensive"],
    },
  }),
  s({
    name: "Grammarly", slug: "grammarly", cat: "writing", domain: "grammarly.com",
    url: "https://www.grammarly.com/", free: "yes", price_type: "freemium", price: "Free / Pro от $12/мес",
    rating: 4.7, popularity: 84, popular: "yes", featured: "no",
    tags: "грамматика, редактура, английский, стиль",
    keywords: "grammarly, грамматика, проверка текста, английский, исправить ошибки, стиль письма, grammar check, перевірка тексту",
    ru: {
      d: "Проверка грамматики, стиля и тона английского текста прямо в браузере, почте и документах.",
      f: ["Проверка грамматики и пунктуации", "Подсказки по стилю и тону", "Переписывание предложений", "Расширение для браузера и Word"],
      p: ["Работает везде, где вы пишете", "Сильный бесплатный тариф", "Экономит время на редактуре"],
      c: ["В основном английский язык", "Лучшие подсказки только в Premium"],
    },
    en: {
      d: "Grammar, style and tone checking for English right inside your browser, mail and documents.",
      f: ["Grammar and punctuation checks", "Style and tone suggestions", "Sentence rewrites", "Browser and Word extensions"],
      p: ["Works everywhere you write", "Strong free tier", "Saves editing time"],
      c: ["Mostly English only", "Best suggestions are Premium"],
    },
  }),
  s({
    name: "QuillBot", slug: "quillbot", cat: "writing", domain: "quillbot.com",
    url: "https://quillbot.com/", free: "yes", price_type: "freemium", price: "Free / от $8.33/мес",
    rating: 4.5, popularity: 62, popular: "no", featured: "no",
    tags: "рерайт, перефразирование, конспект, цитаты",
    keywords: "quillbot, квилбот, перефразировать, рерайт, уникальность текста, сократить текст, paraphrase, перефразувати",
    ru: {
      d: "Перефразирование, сокращение и улучшение текста с несколькими режимами переписывания.",
      f: ["8 режимов перефразирования", "Сокращение длинных текстов", "Проверка грамматики", "Генератор цитат и ссылок"],
      p: ["Очень удобный рерайт", "Есть бесплатный режим", "Поддержка нескольких языков"],
      c: ["Лимит символов на бесплатном тарифе", "Смысл иногда искажается"],
    },
    en: {
      d: "Paraphrasing, summarising and text improvement with several rewriting modes.",
      f: ["8 paraphrasing modes", "Summariser for long texts", "Grammar checker", "Citation generator"],
      p: ["Very convenient rewriting", "Usable free mode", "Multi language support"],
      c: ["Character limit on free plan", "Meaning can drift"],
    },
  }),
  s({
    name: "ElevenLabs", slug: "elevenlabs", cat: "voice", domain: "elevenlabs.io",
    url: "https://elevenlabs.io/", free: "yes", price_type: "freemium", price: "Free / от $5/мес",
    rating: 4.9, popularity: 89, popular: "yes", featured: "yes",
    tags: "озвучка, синтез речи, клонирование голоса, дубляж",
    keywords: "elevenlabs, элевенлабс, озвучить текст, синтез речи, голос, клонировать голос, дубляж, tts, text to speech, озвучити текст",
    ru: {
      d: "Лучший синтез речи: естественная озвучка текста, клонирование голоса и дубляж на 30+ языках.",
      f: ["Реалистичная озвучка текста", "Клонирование собственного голоса", "Дубляж видео на другие языки", "Библиотека готовых голосов"],
      p: ["Самое естественное звучание", "Отличная поддержка русского языка", "Есть бесплатные символы каждый месяц"],
      c: ["Бесплатный лимит небольшой", "Коммерческое использование только на платных тарифах"],
    },
    en: {
      d: "The best text to speech: natural voice over, voice cloning and dubbing in 30+ languages.",
      f: ["Realistic text to speech", "Clone your own voice", "Video dubbing into other languages", "Library of ready voices"],
      p: ["Most natural sounding voices", "Great multilingual support", "Free characters every month"],
      c: ["Small free quota", "Commercial use requires a paid plan"],
    },
  }),
  s({
    name: "Murf AI", slug: "murf-ai", cat: "voice", domain: "murf.ai",
    url: "https://murf.ai/", free: "yes", price_type: "freemium", price: "Free / от $19/мес",
    rating: 4.5, popularity: 56, popular: "no", featured: "no",
    tags: "озвучка, дикторы, презентации, реклама",
    keywords: "murf ai, мурф, озвучка видео, диктор, голос для презентации, voiceover, озвучення відео",
    ru: {
      d: "Студия озвучки с профессиональными AI-дикторами для презентаций, рекламы и обучающих видео.",
      f: ["200+ голосов на 20+ языках", "Настройка темпа, пауз и акцентов", "Синхронизация голоса с видео", "Совместная работа над проектами"],
      p: ["Профессиональное дикторское звучание", "Удобный таймлайн-редактор", "Хорошо для корпоративных видео"],
      c: ["Бесплатный тариф без экспорта", "Дороже конкурентов"],
    },
    en: {
      d: "A voice over studio with professional AI narrators for presentations, ads and training videos.",
      f: ["200+ voices in 20+ languages", "Pace, pause and emphasis control", "Sync voice with video", "Team collaboration"],
      p: ["Professional narration quality", "Convenient timeline editor", "Great for corporate video"],
      c: ["No export on the free plan", "Pricier than competitors"],
    },
  }),
  s({
    name: "Descript", slug: "descript", cat: "voice", domain: "descript.com",
    url: "https://www.descript.com/", free: "yes", price_type: "freemium", price: "Free / от $12/мес",
    rating: 4.5, popularity: 59, popular: "no", featured: "no",
    tags: "подкасты, транскрипция, монтаж текстом, шумоподавление",
    keywords: "descript, дескрипт, транскрипция, расшифровка аудио, монтаж подкаста, убрать шум, transcription, транскрипція",
    ru: {
      d: "Монтаж видео и подкастов через редактирование текстовой расшифровки — удаляете слово, исчезает и звук.",
      f: ["Автоматическая транскрипция", "Монтаж видео через текст", "Удаление слов-паразитов", "Студийное шумоподавление"],
      p: ["Радикально ускоряет монтаж подкастов", "Точная расшифровка", "Всё в одном инструменте"],
      c: ["Кривая обучения для новичков", "Русская транскрипция слабее английской"],
    },
    en: {
      d: "Edit video and podcasts by editing the transcript — delete a word and the audio goes with it.",
      f: ["Automatic transcription", "Edit video via text", "Filler word removal", "Studio grade noise removal"],
      p: ["Massively speeds up podcast editing", "Accurate transcripts", "All in one tool"],
      c: ["Learning curve for beginners", "Non English transcription is weaker"],
    },
  }),
  s({
    name: "Suno", slug: "suno", cat: "music", domain: "suno.com",
    url: "https://suno.com/", free: "yes", price_type: "freemium", price: "Free / от $8/мес",
    rating: 4.8, popularity: 83, popular: "yes", featured: "yes",
    tags: "музыка, песни, вокал, треки",
    keywords: "suno, суно, создать музыку, написать песню, генерация музыки, трек, вокал, music generation, створити музику",
    ru: {
      d: "Генерирует полноценные песни с вокалом и текстом по короткому описанию — от поп-хита до саундтрека.",
      f: ["Песни с вокалом по описанию", "Генерация текста песни", "Любые жанры и языки", "Продление и переработка треков"],
      p: ["Удивительное качество вокала", "Бесплатные кредиты каждый день", "Очень простой ввод"],
      c: ["Коммерческая лицензия только на платных тарифах", "Не всегда попадает в заданный стиль"],
    },
    en: {
      d: "Generates complete songs with vocals and lyrics from a short description — from pop hits to soundtracks.",
      f: ["Songs with vocals from a prompt", "Lyrics generation", "Any genre and language", "Extend and remix tracks"],
      p: ["Surprisingly good vocals", "Free credits every day", "Extremely simple input"],
      c: ["Commercial licence requires a paid plan", "Style matching is hit or miss"],
    },
  }),
  s({
    name: "Udio", slug: "udio", cat: "music", domain: "udio.com",
    url: "https://www.udio.com/", free: "yes", price_type: "freemium", price: "Free / от $10/мес",
    rating: 4.6, popularity: 57, popular: "no", featured: "no",
    tags: "музыка, треки, инструментал, ремиксы",
    keywords: "udio, удио, генерация музыки, инструментал, бит, ремикс, music ai, генерація музики",
    ru: {
      d: "Генератор музыки с акцентом на качество звучания и тонкий контроль над структурой трека.",
      f: ["Генерация треков по описанию", "Контроль структуры композиции", "Расширение и редактирование фрагментов", "Инструментальные версии"],
      p: ["Чистое студийное звучание", "Гибкая работа с частями трека", "Есть бесплатные генерации"],
      c: ["Меньше жанров, чем у Suno", "Очередь в часы пик"],
    },
    en: {
      d: "A music generator focused on audio quality and fine control over track structure.",
      f: ["Track generation from a prompt", "Song structure control", "Extend and edit sections", "Instrumental versions"],
      p: ["Clean studio sound", "Flexible section editing", "Free generations included"],
      c: ["Fewer genres than Suno", "Queues at peak times"],
    },
  }),
];

const PART5 = [
  s({
    name: "GitHub Copilot", slug: "github-copilot", cat: "code", domain: "github.com",
    url: "https://github.com/features/copilot", free: "yes", price_type: "freemium", price: "Free / от $10/мес",
    rating: 4.8, popularity: 91, popular: "yes", featured: "yes",
    tags: "код, автодополнение, ide, ревью",
    keywords: "github copilot, копайлот, написать код, автодополнение кода, программирование, ide, code assistant, написати код",
    ru: {
      d: "AI-помощник программиста прямо в редакторе: дописывает код, объясняет его и предлагает правки в pull request.",
      f: ["Автодополнение кода в реальном времени", "Чат по вашему репозиторию", "Автоматическое ревью pull request", "Поддержка VS Code, JetBrains, Neovim"],
      p: ["Заметно ускоряет разработку", "Понимает контекст проекта", "Есть бесплатный тариф"],
      c: ["Иногда предлагает неверный код", "Нужна проверка безопасности предложений"],
    },
    en: {
      d: "An AI pair programmer inside your editor: completes code, explains it and suggests pull request fixes.",
      f: ["Real time code completion", "Chat about your repository", "Automatic pull request review", "VS Code, JetBrains and Neovim support"],
      p: ["Noticeably faster development", "Understands project context", "Free tier available"],
      c: ["Sometimes suggests wrong code", "Suggestions need security review"],
    },
  }),
  s({
    name: "Cursor", slug: "cursor", cat: "code", domain: "cursor.com",
    url: "https://cursor.com/", free: "yes", price_type: "freemium", price: "Free / Pro $20/мес",
    rating: 4.8, popularity: 87, popular: "yes", featured: "yes",
    tags: "код, ide, агент, рефакторинг",
    keywords: "cursor, курсор, редактор кода, ai ide, написать приложение, рефакторинг, агент, редактор коду",
    ru: {
      d: "Редактор кода с AI-агентом, который понимает весь проект и способен сам вносить изменения в несколько файлов.",
      f: ["Агент, редактирующий несколько файлов", "Чат с контекстом всего проекта", "Умное автодополнение", "Импорт настроек из VS Code"],
      p: ["Очень мощный агентский режим", "Знает структуру всего репозитория", "Быстрая работа"],
      c: ["Лимиты запросов на бесплатном тарифе", "Требует контроля изменений"],
    },
    en: {
      d: "A code editor with an AI agent that understands the whole project and can edit multiple files on its own.",
      f: ["Agent that edits multiple files", "Chat with full project context", "Smart autocompletion", "Imports your VS Code setup"],
      p: ["Very strong agent mode", "Knows the whole repository", "Fast and responsive"],
      c: ["Request limits on the free plan", "Changes need review"],
    },
  }),
  s({
    name: "Windsurf", slug: "windsurf", cat: "code", domain: "windsurf.com",
    url: "https://windsurf.com/", free: "yes", price_type: "freemium", price: "Free / от $15/мес",
    rating: 4.5, popularity: 54, popular: "no", featured: "no",
    tags: "код, агент, ide, автодополнение",
    keywords: "windsurf, codeium, виндсерф, ai редактор, написать код бесплатно, агент, автодоповнення коду",
    ru: {
      d: "AI-редактор кода с агентским режимом Cascade и щедрым бесплатным автодополнением.",
      f: ["Агентский режим Cascade", "Бесплатное автодополнение кода", "Понимание контекста репозитория", "Плагины для популярных IDE"],
      p: ["Хороший бесплатный тариф", "Простой и чистый интерфейс", "Быстрые подсказки"],
      c: ["Модели слабее, чем у лидеров", "Меньше сообщество"],
    },
    en: {
      d: "An AI code editor with the Cascade agent mode and generous free code completion.",
      f: ["Cascade agent mode", "Free code completion", "Repository context awareness", "Plugins for popular IDEs"],
      p: ["Good free tier", "Clean, simple interface", "Fast suggestions"],
      c: ["Models weaker than leaders", "Smaller community"],
    },
  }),
  s({
    name: "v0 by Vercel", slug: "v0", cat: "code", domain: "v0.dev",
    url: "https://v0.dev/", free: "yes", price_type: "freemium", price: "Free / от $20/мес",
    rating: 4.5, popularity: 61, popular: "no", featured: "no",
    tags: "интерфейсы, react, ui, прототипы",
    keywords: "v0, версель, создать сайт, интерфейс, ui генератор, react компонент, лендинг, створити сайт",
    ru: {
      d: "Генерирует готовые веб-интерфейсы и React-компоненты по текстовому описанию или скриншоту.",
      f: ["Генерация UI по описанию", "Готовый код React и Tailwind", "Правки интерфейса в диалоге", "Публикация проекта в один клик"],
      p: ["Мгновенные прототипы интерфейсов", "Чистый современный код", "Есть бесплатные кредиты"],
      c: ["Заточен под стек React/Tailwind", "Сложную логику пишет хуже"],
    },
    en: {
      d: "Generates ready web interfaces and React components from a description or a screenshot.",
      f: ["UI generation from a prompt", "Ready React and Tailwind code", "Iterate on the design in chat", "One click deploy"],
      p: ["Instant UI prototypes", "Clean modern code", "Free credits included"],
      c: ["Tied to the React/Tailwind stack", "Weaker at complex logic"],
    },
  }),
  s({
    name: "Gamma", slug: "gamma", cat: "business", domain: "gamma.app",
    url: "https://gamma.app/", free: "yes", price_type: "freemium", price: "Free / от $10/мес",
    rating: 4.6, popularity: 73, popular: "yes", featured: "no",
    tags: "презентации, слайды, документы, сайты",
    keywords: "gamma, гамма, сделать презентацию, слайды, питч дек, презентация из текста, presentation, зробити презентацію",
    ru: {
      d: "Создаёт готовую презентацию, документ или мини-сайт из одной строки описания за минуту.",
      f: ["Презентация по текстовому запросу", "Автоматический дизайн слайдов", "Экспорт в PowerPoint и PDF", "Аналитика просмотров"],
      p: ["Красивые слайды без дизайнера", "Очень быстрый результат", "Щедрый бесплатный тариф"],
      c: ["Ограниченная кастомизация шаблонов", "Кредиты на бесплатном плане"],
    },
    en: {
      d: "Creates a finished presentation, document or micro site from a one line prompt in about a minute.",
      f: ["Presentation from a text prompt", "Automatic slide design", "Export to PowerPoint and PDF", "View analytics"],
      p: ["Beautiful slides without a designer", "Extremely fast results", "Generous free tier"],
      c: ["Limited template customisation", "Credit based free plan"],
    },
  }),
  s({
    name: "Zapier", slug: "zapier", cat: "business", domain: "zapier.com",
    url: "https://zapier.com/", free: "yes", price_type: "freemium", price: "Free / от $19.99/мес",
    rating: 4.6, popularity: 69, popular: "no", featured: "no",
    tags: "автоматизация, интеграции, процессы, боты",
    keywords: "zapier, запиер, автоматизация, интеграция сервисов, без кода, workflow, автоматизація, no code",
    ru: {
      d: "Автоматизация рабочих процессов между 7000+ сервисов с AI-шагами — без единой строчки кода.",
      f: ["Интеграции с 7000+ сервисами", "AI-шаги внутри сценариев", "Конструктор ботов и агентов", "Таблицы и интерфейсы"],
      p: ["Огромное количество интеграций", "Не нужен программист", "Есть бесплатный тариф"],
      c: ["Цена растёт с числом задач", "Сложные сценарии требуют времени"],
    },
    en: {
      d: "Workflow automation across 7000+ apps with AI steps — without writing a single line of code.",
      f: ["7000+ app integrations", "AI steps inside workflows", "Bot and agent builder", "Tables and interfaces"],
      p: ["Huge integration catalog", "No developer needed", "Free tier available"],
      c: ["Cost grows with task volume", "Complex flows take time to build"],
    },
  }),
  s({
    name: "Otter.ai", slug: "otter-ai", cat: "business", domain: "otter.ai",
    url: "https://otter.ai/", free: "yes", price_type: "freemium", price: "Free / от $8.33/мес",
    rating: 4.5, popularity: 52, popular: "no", featured: "no",
    tags: "встречи, транскрипция, заметки, zoom",
    keywords: "otter ai, оттер, запись встречи, транскрипция, заметки со встречи, zoom, meeting notes, транскрипція зустрічі",
    ru: {
      d: "Записывает и расшифровывает встречи в Zoom, Meet и Teams, формируя краткое резюме и список задач.",
      f: ["Живая транскрипция встреч", "Автоматическое резюме и задачи", "Подключение к Zoom, Meet, Teams", "Поиск по всем встречам"],
      p: ["Не нужно вести конспект вручную", "Хорошая точность на английском", "Есть бесплатные минуты"],
      c: ["Русский язык поддерживается слабо", "Лимит минут на бесплатном тарифе"],
    },
    en: {
      d: "Records and transcribes Zoom, Meet and Teams calls, then produces a summary and action items.",
      f: ["Live meeting transcription", "Automatic summary and action items", "Zoom, Meet and Teams integration", "Search across all meetings"],
      p: ["No manual note taking", "High accuracy in English", "Free minutes included"],
      c: ["Weak non English support", "Minute limits on the free plan"],
    },
  }),
  s({
    name: "Buffer", slug: "buffer", cat: "social", domain: "buffer.com",
    url: "https://buffer.com/", free: "yes", price_type: "freemium", price: "Free / от $6/канал",
    rating: 4.4, popularity: 50, popular: "no", featured: "no",
    tags: "smm, планирование, публикации, аналитика",
    keywords: "buffer, буфер, отложенный постинг, планирование постов, smm, соцсети, аналитика, планування постів",
    ru: {
      d: "Планировщик публикаций для соцсетей с AI-ассистентом, который помогает писать и адаптировать посты.",
      f: ["Отложенный постинг во все соцсети", "AI-ассистент для текстов постов", "Адаптация поста под каждую площадку", "Аналитика вовлечённости"],
      p: ["Простой и понятный интерфейс", "Бесплатно до 3 каналов", "Экономит время SMM-специалиста"],
      c: ["Аналитика только на платных тарифах", "AI-ассистент базовый"],
    },
    en: {
      d: "A social media scheduler with an AI assistant that helps write and adapt posts.",
      f: ["Scheduling for all major networks", "AI assistant for post copy", "Per platform post adaptation", "Engagement analytics"],
      p: ["Simple, clear interface", "Free for up to 3 channels", "Saves social manager time"],
      c: ["Analytics are paid only", "AI assistant is basic"],
    },
  }),
  s({
    name: "Predis.ai", slug: "predis-ai", cat: "social", domain: "predis.ai",
    url: "https://predis.ai/", free: "yes", price_type: "freemium", price: "Free / от $32/мес",
    rating: 4.3, popularity: 44, popular: "no", featured: "no",
    tags: "креативы, посты, карусели, инстаграм",
    keywords: "predis ai, предис, создать пост, креатив для инстаграм, карусель, реклама, smm, створити пост",
    ru: {
      d: "Генерирует готовые креативы для соцсетей: карусели, посты и короткие видео вместе с текстом и хэштегами.",
      f: ["Генерация постов и каруселей", "Короткие видео для Reels", "Подбор хэштегов", "Планировщик публикаций"],
      p: ["Полностью готовый визуал и текст", "Быстро закрывает контент-план", "Есть бесплатные генерации"],
      c: ["Шаблонный дизайн креативов", "Платные тарифы дорогие"],
    },
    en: {
      d: "Generates ready social creatives: carousels, posts and short videos with copy and hashtags included.",
      f: ["Post and carousel generation", "Short videos for Reels", "Hashtag suggestions", "Publishing scheduler"],
      p: ["Complete visual plus copy", "Fills a content plan fast", "Free generations included"],
      c: ["Template-looking designs", "Paid plans are expensive"],
    },
  }),
];

const PART6 = [
  s({
    name: "ChatPDF", slug: "chatpdf", cat: "documents", domain: "chatpdf.com",
    url: "https://www.chatpdf.com/", free: "yes", price_type: "freemium", price: "Free / от $5/мес",
    rating: 4.5, popularity: 53, popular: "no", featured: "no",
    tags: "pdf, документы, вопросы по файлу, конспект",
    keywords: "chatpdf, чат пдф, вопросы по pdf, прочитать документ, конспект договора, анализ pdf, документи",
    ru: {
      d: "Загрузите PDF и задавайте вопросы по документу — сервис отвечает и указывает нужные страницы.",
      f: ["Вопросы по содержимому PDF", "Ссылки на страницы в ответах", "Краткое резюме документа", "Поддержка нескольких языков"],
      p: ["Мгновенно находит нужное в договоре", "Простой интерфейс", "Есть бесплатный тариф"],
      c: ["Лимит страниц и файлов бесплатно", "Не подходит для сканов плохого качества"],
    },
    en: {
      d: "Upload a PDF and ask questions about it — the service answers and points to the exact pages.",
      f: ["Ask questions about a PDF", "Page citations in answers", "Document summary", "Multi language support"],
      p: ["Finds contract details instantly", "Very simple interface", "Free tier available"],
      c: ["Page and file limits when free", "Struggles with poor scans"],
    },
  }),
  s({
    name: "Humata", slug: "humata", cat: "documents", domain: "humata.ai",
    url: "https://www.humata.ai/", free: "yes", price_type: "freemium", price: "Free / от $9.99/мес",
    rating: 4.3, popularity: 40, popular: "no", featured: "no",
    tags: "документы, исследования, отчёты, анализ",
    keywords: "humata, хумата, анализ документов, исследование, научная статья, отчет, document ai, аналіз документів",
    ru: {
      d: "Анализ больших наборов документов: сравнивает файлы, отвечает на вопросы и готовит выводы со ссылками.",
      f: ["Работа сразу с несколькими файлами", "Ответы со ссылками на источник", "Сравнение документов", "Генерация отчётов"],
      p: ["Хорошо справляется с научными текстами", "Точные ссылки на источники", "Есть бесплатные страницы"],
      c: ["Интерфейс только на английском", "Дороже простых аналогов"],
    },
    en: {
      d: "Analyses large document sets: compares files, answers questions and produces conclusions with citations.",
      f: ["Work across multiple files", "Answers with source citations", "Document comparison", "Report generation"],
      p: ["Handles academic texts well", "Precise citations", "Free pages included"],
      c: ["English only interface", "Pricier than simple alternatives"],
    },
  }),
  s({
    name: "DeepL", slug: "deepl", cat: "translation", domain: "deepl.com",
    url: "https://www.deepl.com/", free: "yes", price_type: "freemium", price: "Free / от $8.74/мес",
    rating: 4.8, popularity: 85, popular: "yes", featured: "yes",
    tags: "перевод, документы, глоссарий, качество",
    keywords: "deepl, дипл, перевести текст, перевод документа, переводчик, translate, точный перевод, перекласти текст",
    ru: {
      d: "Самый естественный машинный перевод: сохраняет смысл и стиль, переводит документы целиком с форматированием.",
      f: ["Перевод на 30+ языков", "Перевод файлов Word, PDF, PPT", "Глоссарий терминов", "AI-редактор стиля письма"],
      p: ["Заметно точнее обычных переводчиков", "Сохраняет форматирование документов", "Хороший бесплатный тариф"],
      c: ["Лимит символов бесплатно", "Меньше языков, чем у конкурентов"],
    },
    en: {
      d: "The most natural machine translation: keeps meaning and tone, and translates whole documents with formatting.",
      f: ["30+ languages", "Word, PDF and PPT file translation", "Terminology glossary", "AI writing style editor"],
      p: ["Noticeably more accurate", "Preserves document formatting", "Good free tier"],
      c: ["Character limits when free", "Fewer languages than rivals"],
    },
  }),
  s({
    name: "Smartcat", slug: "smartcat", cat: "translation", domain: "smartcat.com",
    url: "https://www.smartcat.com/", free: "yes", price_type: "freemium", price: "Free / по запросу",
    rating: 4.3, popularity: 38, popular: "no", featured: "no",
    tags: "локализация, перевод сайтов, команды, память переводов",
    keywords: "smartcat, смарткат, локализация, перевод сайта, память переводов, команда переводчиков, локалізація",
    ru: {
      d: "Платформа локализации для команд: AI-перевод, память переводов и совместная работа редакторов.",
      f: ["AI-перевод с памятью переводов", "Локализация сайтов и приложений", "Совместная работа команды", "Маркетплейс переводчиков"],
      p: ["Подходит для больших проектов", "Единый глоссарий на всю команду", "Есть бесплатный старт"],
      c: ["Избыточен для одиночных задач", "Непрозрачное ценообразование"],
    },
    en: {
      d: "A localisation platform for teams: AI translation, translation memory and collaborative editing.",
      f: ["AI translation with translation memory", "Website and app localisation", "Team collaboration", "Translator marketplace"],
      p: ["Great for large projects", "Shared glossary across the team", "Free entry plan"],
      c: ["Overkill for one off tasks", "Opaque pricing"],
    },
  }),
  s({
    name: "Khanmigo", slug: "khanmigo", cat: "education", domain: "khanmigo.org",
    url: "https://www.khanmigo.org/", free: "no", price_type: "paid", price: "от $4/мес",
    rating: 4.4, popularity: 42, popular: "no", featured: "no",
    tags: "учёба, репетитор, школа, математика",
    keywords: "khanmigo, ханмиго, репетитор, помощь с уроками, математика, объяснить тему, учеба, tutor, навчання",
    ru: {
      d: "AI-репетитор от Khan Academy: не даёт готовый ответ, а ведёт ученика к решению наводящими вопросами.",
      f: ["Пошаговое объяснение задач", "Подсказки вместо готовых ответов", "Помощь по математике и естественным наукам", "Инструменты для учителей"],
      p: ["Действительно учит, а не решает за ученика", "Проверенная методика Khan Academy", "Низкая цена"],
      c: ["Нет бесплатного тарифа", "Контент в основном на английском"],
    },
    en: {
      d: "Khan Academy's AI tutor: instead of handing over answers, it guides the student with leading questions.",
      f: ["Step by step problem explanations", "Hints instead of answers", "Math and science help", "Tools for teachers"],
      p: ["Actually teaches instead of solving", "Proven Khan Academy method", "Low price"],
      c: ["No free plan", "Content mostly in English"],
    },
  }),
  s({
    name: "Duolingo", slug: "duolingo", cat: "education", domain: "duolingo.com",
    url: "https://www.duolingo.com/", free: "yes", price_type: "freemium", price: "Free / Super от $6.99/мес",
    rating: 4.7, popularity: 79, popular: "yes", featured: "no",
    tags: "языки, английский, практика, разговор",
    keywords: "duolingo, дуолинго, выучить английский, изучение языков, практика разговора, язык, learn english, вивчити англійську",
    ru: {
      d: "Изучение языков в формате игры с AI-функциями: разговорная практика и объяснение ошибок.",
      f: ["40+ языков в игровом формате", "Разговорная практика с AI", "Объяснение каждой ошибки", "Ежедневные короткие уроки"],
      p: ["Затягивает и держит привычку", "Много бесплатного контента", "Удобно на телефоне"],
      c: ["AI-функции только в Max-подписке", "Не заменяет живую практику"],
    },
    en: {
      d: "Gamified language learning with AI features: conversation practice and explanations for every mistake.",
      f: ["40+ languages, gamified", "AI conversation practice", "Explanation for every mistake", "Short daily lessons"],
      p: ["Addictive and habit forming", "Lots of free content", "Great mobile experience"],
      c: ["AI features need the Max plan", "Not a replacement for real practice"],
    },
  }),
];

export const SERVICES = [...PART1, ...PART2, ...PART3, ...PART4, ...PART5, ...PART6];
